# Numpy
### Resources:
- An introduction to Numpy and Scipy

### import numpy module

In [842]:
import numpy as np

## Arrays

In [843]:
a = np.array([1,2,3,4,5,6,7,8], float)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [844]:
type(a)

numpy.ndarray

In [845]:
a.shape

(8L,)

### Slicing

In [846]:
a[3]

4.0

In [847]:
a[1:3]

array([ 2.,  3.])

In [848]:
a[:3]

array([ 1.,  2.,  3.])

In [849]:
a[::2]

array([ 1.,  3.,  5.,  7.])

In [850]:
a[::-1]

array([ 8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [851]:
a[::-2]

array([ 8.,  6.,  4.,  2.])

In [852]:
print a[-1]
print a[-2]
print a[-3]

8.0
7.0
6.0


### 2-D Array

In [853]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Again Slicing

In [854]:
a[0][0]

1

In [855]:
a[1,2]

9

In [856]:
print a[0,:]
print a[1,:]

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [857]:
print a[:,0]
print a[:,3]

[1 7]
[ 4 10]


In [858]:
a[-1:,-2:]

array([[11, 12]])

### find

In [859]:
2 in a

True

In [860]:
13 in a

False

### Type, Shape, Size, length, dimension

In [861]:
a.dtype

dtype('int32')

In [862]:
a.shape

(2L, 6L)

In [863]:
print a.shape[0]
print a.shape[1]

2
6


In [864]:
len(a)

2

In [865]:
a.ndim

2

In [866]:
a.size

12

### arange

In [867]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [868]:
a = np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### reshape

In [869]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [870]:
a = a.reshape((3,4))
a              

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### copy

In [871]:
a = np.array(range(10))
b = a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [872]:
c = a.copy()
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### tolist

In [873]:
a = np.array(range(8))
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [874]:
b = a.tolist()
b

[0, 1, 2, 3, 4, 5, 6, 7]

In [875]:
c = list(a)
c

[0, 1, 2, 3, 4, 5, 6, 7]

### tostring, fromstring

In [876]:
a = np.array([1,2,3,4], float)
a

array([ 1.,  2.,  3.,  4.])

In [877]:
s = a.tostring()
s

'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@'

In [878]:
b = np.fromstring(s)
b

array([ 1.,  2.,  3.,  4.])

### fill

In [879]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [880]:
a.fill(0)
a

array([0, 0, 0, 0])

### Transpose

In [881]:
a = np.array(range(6)).reshape((2,3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [882]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [883]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### flatten

In [884]:
a = np.array(np.arange(12)).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [885]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### concatenate

In [886]:
a = np.array([1,2,3])
b = np.array([4,5])
c = np.array([6,7,8,9])
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Horizontal Concatenation

In [887]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print a
print b

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [888]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### Vertical Concatenation

In [889]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Create Special Arrays

### arange

In [890]:
a = np.arange(10, dtype=float)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [891]:
a = np.arange(2, 7)
a

array([2, 3, 4, 5, 6])

In [892]:
a = np.arange(3, 10, 2)
a

array([3, 5, 7, 9])

### Ones

In [893]:
a = np.ones(5, dtype=float)
a

array([ 1.,  1.,  1.,  1.,  1.])

In [894]:
a = np.ones((3,4))
a

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

### Zeros

In [895]:
a = np.zeros((3,3))
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [896]:
b = np.array(np.arange(6)).reshape(2,3)
print b
a = np.zeros_like(b)
print a

[[0 1 2]
 [3 4 5]]
[[0 0 0]
 [0 0 0]]


### Identity

In [897]:
a = np.eye(4)
a

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Array Mathematics

### elementwise operations:

In [898]:
a = np.array([1,2,3], float)
b = np.array([4,5,6], float)

In [899]:
a+b

array([ 5.,  7.,  9.])

In [900]:
a-b

array([-3., -3., -3.])

In [901]:
a*b

array([  4.,  10.,  18.])

In [902]:
a/b

array([ 0.25,  0.4 ,  0.5 ])

In [903]:
a**b

array([   1.,   32.,  729.])

In [904]:
a%b

array([ 1.,  2.,  3.])

In [905]:
a*2

array([ 2.,  4.,  6.])

In [906]:
a**2

array([ 1.,  4.,  9.])

In [907]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,2],[-1,2]])

In [908]:
a*b

array([[ 3,  4],
       [-3,  8]])

In [909]:
a+2

array([[3, 4],
       [5, 6]])

In [910]:
a+np.array([7,1])

array([[ 8,  3],
       [10,  5]])

## newaxis

### More advanced Operations:

__abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, and arctanh__

In [911]:
a = np.array([1,4,9,16])
a

array([ 1,  4,  9, 16])

In [912]:
np.sqrt(a)

array([ 1.,  2.,  3.,  4.])

__sum, prod, mean, var, std__

In [913]:
a = np.array([[1,2,3],[4,5,6]])

In [914]:
print a.sum()
print a.sum(axis=0)
print a.sum(axis=1)

21
[5 7 9]
[ 6 15]


In [915]:
a.prod()

720

In [916]:
a.mean()

3.5

In [917]:
a.var()

2.9166666666666665

In [918]:
a.std()

1.707825127659933

__min, max, argmin, argmax__

In [919]:
a = np.array([[1,9,2,8], [5,6,7,4]])
a

array([[1, 9, 2, 8],
       [5, 6, 7, 4]])

In [920]:
a.min()

1

In [921]:
a.min(axis=0)

array([1, 6, 2, 4])

In [922]:
a.min(axis=1)

array([1, 4])

In [923]:
a.max()

9

In [924]:
a.max(axis=0)

array([5, 9, 7, 8])

In [925]:
a.max(axis=1)

array([9, 7])

In [926]:
a.argmin()

0

In [927]:
a.argmin(axis=0)

array([0, 1, 0, 1], dtype=int64)

In [928]:
a.argmin(axis=1)

array([0, 3], dtype=int64)

In [929]:
a.argmax()

1

In [930]:
a.argmax(axis=0)

array([1, 0, 1, 0], dtype=int64)

In [931]:
a.argmax(axis=1)

array([1, 2], dtype=int64)

__sort__

In [932]:
a = np.array([[1,9,2,8], [5,6,7,4]])
print a
a.sort()
print a

[[1 9 2 8]
 [5 6 7 4]]
[[1 2 8 9]
 [4 5 6 7]]


In [933]:
a = np.array([[1,9,2,8], [5,6,7,4]])
a.sort(axis=0)
a

array([[1, 6, 2, 4],
       [5, 9, 7, 8]])

In [934]:
a = np.array([[1,9,2,8], [5,6,7,4]])
a.sort(axis=1)
a

array([[1, 2, 8, 9],
       [4, 5, 6, 7]])

In [935]:
a = np.array([[1,9,2,8], [5,6,7,4]])
np.sort(a, axis=None)

array([1, 2, 4, 5, 6, 7, 8, 9])

__floor, ceil, rint__

In [936]:
a = np.array([1.1, 1.5, 1.9])
a

array([ 1.1,  1.5,  1.9])

In [937]:
np.ceil(a)

array([ 2.,  2.,  2.])

In [938]:
np.floor(a)

array([ 1.,  1.,  1.])

In [939]:
np.rint(a)

array([ 1.,  2.,  2.])

__pi__

In [940]:
np.pi

3.141592653589793

### clip

In [941]:
a = np.array([1,2,6,-2,9,5])
a

array([ 1,  2,  6, -2,  9,  5])

In [942]:
a.clip(0,5)

array([1, 2, 5, 0, 5, 5])

### unique

In [943]:
a = np.array([1,2,2,4,4,4,5,1])
a

array([1, 2, 2, 4, 4, 4, 5, 1])

In [944]:
np.unique(a)

array([1, 2, 4, 5])

### diagonal

In [945]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [946]:
a.diagonal()

array([1, 4])

### Comparison operators and value testing

In [947]:
a = np.array([1,2,4])
b = np.array([3,1,4])
a == b

array([False, False,  True], dtype=bool)

In [948]:
a>b

array([False,  True, False], dtype=bool)

In [949]:
a<=b

array([ True, False,  True], dtype=bool)

In [950]:
a>2

array([False, False,  True], dtype=bool)

In [951]:
c = a>b
c

array([False,  True, False], dtype=bool)

__any__

In [952]:
c.any()

True

__all__

In [953]:
c.all()

False

__logical_and__, __logical_or__, __logical_not__

In [954]:
a = np.array([1,2,4,5,3,6,5,8,9])
a

array([1, 2, 4, 5, 3, 6, 5, 8, 9])

In [955]:
np.logical_and(a>2, a<5)

array([False, False,  True, False,  True, False, False, False, False], dtype=bool)

In [956]:
np.logical_or(a<3, a>6)

array([ True,  True, False, False, False, False, False,  True,  True], dtype=bool)

In [957]:
np.logical_not(a>5)

array([ True,  True,  True,  True,  True, False,  True, False, False], dtype=bool)

__where__

In [958]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [959]:
np.where(a>3)

(array([3, 4, 5], dtype=int64),)

In [960]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [961]:
np.where(a<6)

(array([0, 0, 0, 0, 1], dtype=int64), array([0, 1, 2, 3, 0], dtype=int64))

__nonzero__

In [962]:
a = np.array([[1,0],[3,0]])
a

array([[1, 0],
       [3, 0]])

In [963]:
np.nonzero(a)

(array([0, 1], dtype=int64), array([0, 0], dtype=int64))

__isnan__

In [964]:
a = np.array([1, np.NaN, np.Inf])
a

array([  1.,  nan,  inf])

In [965]:
np.isnan(a)

array([False,  True, False], dtype=bool)

__isfinite__

In [966]:
np.isinf(a)

array([False, False,  True], dtype=bool)

### item selection

In [967]:
a = np.array([[6,4],[5,9]])
a

array([[6, 4],
       [5, 9]])

In [968]:
a >= 6

array([[ True, False],
       [False,  True]], dtype=bool)

In [969]:
a[a>=6]

array([6, 9])

In [970]:
a[np.logical_and(a>5, a<9)]

array([6])

In [971]:
a[a>=6] = 0
a

array([[0, 4],
       [5, 0]])

In [972]:
a = np.array([1,3,2,6,5,7,8,4,8,2,8,0,9])
a

array([1, 3, 2, 6, 5, 7, 8, 4, 8, 2, 8, 0, 9])

In [973]:
idx = np.random.randint(0,10,size=10)
idx

array([9, 0, 0, 6, 2, 7, 3, 7, 2, 0])

In [974]:
a[idx]

array([2, 1, 1, 8, 2, 4, 6, 4, 2, 1])

In [975]:
a[[0,2,3,1,0]]

array([1, 2, 6, 3, 1])

In [976]:
a = np.random.randint(0,10,size=(3,4))
a

array([[4, 2, 7, 0],
       [4, 5, 7, 2],
       [5, 8, 0, 7]])

In [977]:
x_ind = [0,1,2,1,2,0]
y_ind = [0,1,3,2,1,3]
a[x_ind, y_ind]

array([4, 5, 7, 7, 8, 0])

__take__

In [978]:
a = np.array([1,3,2,4,5,6])
b = np.array([0,0,1,3,4,5,2,3])
a.take(b)

array([1, 1, 3, 4, 5, 6, 2, 4])

In [979]:
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
b = np.array([0,1,0,1])

In [980]:
a.take(b, axis=0)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [981]:
a.take(b, axis=1)

array([[1, 2, 1, 2],
       [6, 7, 6, 7]])

__put__

In [982]:
a = np.array(np.arange(10))
b = np.array([7,8,9])
a.put([0,1,3,5,7,8],b)
a

array([7, 8, 2, 9, 4, 7, 6, 8, 9, 9])

### Vector and matrix mathematics

__dot__

In [983]:
a = np.array([1,2,3,4,5])
b = np.array([0,3,2,1,0])
np.dot(a,b)

16

In [984]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,-2],[-3,4]])
np.dot(a,b)

array([[-5,  6],
       [-9, 10]])

In [985]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,-1,2])

In [986]:
np.dot(a,b)

array([ 5, 11, 17])

In [987]:
np.dot(b,a)

array([11, 13, 15])

__outer__

In [988]:
a = np.array([[1,2,3,4,5]])
b = np.array([1,2,3])

In [989]:
np.outer(a,b)

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15]])

In [990]:
np.outer(b,a)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])

In [991]:
a = np.array([[1,2],[3,4]])
b = np.array([[0,1],[-1,2]])

In [992]:
np.outer(a,b)

array([[ 0,  1, -1,  2],
       [ 0,  2, -2,  4],
       [ 0,  3, -3,  6],
       [ 0,  4, -4,  8]])

In [993]:
np.outer(b,a)

array([[ 0,  0,  0,  0],
       [ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 2,  4,  6,  8]])

__inner__

In [994]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,2,1])

In [995]:
np.inner(a,b)

27

In [996]:
a = np.array([[1,2],[3,4]])
b = np.array([1,-2])

In [997]:
np.inner(a,b)

array([-3, -5])

In [998]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,-2],[0,7]])

In [999]:
np.inner(a,b)

array([[-3, 14],
       [-5, 28]])

In [1000]:
np.inner(b,a)

array([[-3, -5],
       [14, 28]])

__cross__

$ u \times v =
\begin{vmatrix}
i & j & k  \\ 
u_1 & u_2 & u_3  \\ 
v_1 & v_2 & v_3  \notag
\end{vmatrix}$

In [1001]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [1002]:
np.cross(a,b)

array([-3,  6, -3])

In [1003]:
np.cross(b,a)

array([ 3, -6,  3])

### multiply Module

### linear algebra
__linalg__, __linalg.det__, __linalg.eig__, __linalg.inv__, __linalg.svd__

In [1004]:
a = np.array([[1,-2,3],[4,5,6],[7,8,9]])
a

array([[ 1, -2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [1005]:
np.linalg.det(a)

-24.000000000000014

In [1006]:
b = np.linalg.inv(a)
b

array([[ 0.125     , -1.75      ,  1.125     ],
       [-0.25      ,  0.5       , -0.25      ],
       [ 0.125     ,  0.91666667, -0.54166667]])

In [1007]:
np.dot(a,b)

array([[  1.00000000e+00,  -4.44089210e-16,   2.22044605e-16],
       [  0.00000000e+00,   1.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

In [1008]:
vals, vecs = np.linalg.eig(a)
print vals
print vecs

[ 15.02680905   1.25044877  -1.27725782]
[[-0.10159966 -0.83636945 -0.80956208]
 [-0.54035837  0.48575886 -0.04368041]
 [-0.8352786   0.25401668  0.58540692]]


In [1009]:
U, S, V = np.linalg.svd(a)
print U
print S
print V

[[-0.08333344  0.99542563  0.04672632]
 [-0.5310361  -0.00468158 -0.84733627]
 [-0.84324149 -0.0954248   0.52899707]]
[ 16.51087649   3.49542891   0.41585377]
[[-0.49120156 -0.55929469 -0.66776529]
 [ 0.0883227  -0.79465429  0.60060275]
 [ 0.86655648 -0.23603817 -0.43973384]]


### Polynomial mathematics

__get polynomial coefficient from its roots__

In [1010]:
np.poly([1,2,3,4])

array([  1., -10.,  35., -50.,  24.])

__find the roots of a plolynomial__

In [1011]:
np.roots([1,2,3,4])

array([-1.65062919+0.j        , -0.17468540+1.54686889j,
       -0.17468540-1.54686889j])

__integrate the polynomial__

In [1012]:
np.polyint([1,2,3,4])

array([ 0.25      ,  0.66666667,  1.5       ,  4.        ,  0.        ])

__derivative of polynomial__

In [1013]:
np.polyder([1,2,3,4])

array([3, 4, 3])

### Statistics

__median__

In [1014]:
a = np.array([1,4,2,6,5,8,5,9,3])
a

array([1, 4, 2, 6, 5, 8, 5, 9, 3])

In [1015]:
np.median(a)

5.0

__Correlation Coefficient__

In [1016]:
a = np.array([[1,2,3,1],[3,2,4,1]])
a

array([[1, 2, 3, 1],
       [3, 2, 4, 1]])

In [1017]:
np.corrcoef(a)

array([[ 1.        ,  0.67419986],
       [ 0.67419986,  1.        ]])

__Covariance__

In [1018]:
np.cov(a)

array([[ 0.91666667,  0.83333333],
       [ 0.83333333,  1.66666667]])

__Correlation__

### Random numbers

__seed__

__rand__

In [1019]:
a = np.random.rand(5)
a

array([ 0.20274029,  0.77521854,  0.69176767,  0.08096071,  0.59751884])

__randint__

In [1020]:
np.random.randint(1,5)

4

In [1021]:
np.random.randint(2,10, size=5)

array([9, 3, 2, 3, 8])

__normal__

In [1022]:
np.random.normal(2.5, 1)

2.8566153762736866

In [1023]:
np.random.normal()

-0.526384706968776

In [1024]:
np.random.normal(0,3,size=(3,3))

array([[-2.84992998,  1.24198065, -4.40611368],
       [ 0.02865025,  0.19149262, -1.90170669],
       [ 0.56864276,  0.46661185,  7.14131341]])

__poisson__

In [1025]:
np.random.poisson()

0

In [1026]:
np.random.poisson(8,size=(4,3))

array([[ 6, 10,  6],
       [ 7, 10, 11],
       [ 2,  9, 13],
       [ 4, 11, 14]])

__shuffle__

In [1027]:
a = np.array(np.arange(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1028]:
np.random.shuffle(a)
a

array([9, 2, 6, 8, 3, 7, 0, 1, 4, 5])